spring:
  application:
    name: store-service


  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/store-db
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate

#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    url: jdbc:postgresql://localhost:5432/store-db
#    user: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: INFO