spring:
  application:
    name: store-service


  r2dbc:
    username: postgres
    password: postgres
    url: r2dbc:postgresql://localhost:5432/store-db
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 10m
      max-size: 10

  data:
    r2dbc:
      repositories:
        enabled: true

#  liquibase:
#    enabled: true
#    change-log: classpath:/db/changelog/db.changelog-master.yaml
#    url: jdbc:postgresql://localhost:5432/store-db
#    user: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver

logging:
  level:
    root: info